// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdmbnksxrdnejkhfohml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbWJua3N4cmRuZWpraGZvaG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzY0NTksImV4cCI6MjA1OTY1MjQ1OX0.5JGdnNb5tQ0kyVo5NB8awlMpMNapx85SbiVquEZSKys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);